

# * 2020

# ** 2020-10 October

# *** 2020-10-09 Friday

# **** 10:08 AM - Journal                                          :journal:
# :LOGBOOK:
# CLOCK: [2020-10-09 Fri 10:08]--[2020-10-09 Fri 10:08] =>  0:00
# :END:

# Today was a great day!  We learned more about Org Mode.

* 2021

** 2021-12 December

*** 2021-12-08 Wednesday

*** 2021-12-18 Saturday

**** 06:54 AM - Journal                                          :journal:
:LOGBOOK:
CLOCK: [2021-12-18 Sat 06:54]--[2021-12-18 Sat 07:05] =>  0:11
:END:

First time writing journal here in lapotp. It feels preety weird though. The day started almost perfect. In th way it is. I might say fell into desires little bit. Lately i feel  like i'm letting my emotions take over me and it's very frustrating. I really need to change that. I need to implement all those stoic ideas in real life. Just remember only thing you've control over is your preconception and nothing else. Like the day i was angry because i was ignoran t and stupid. I feel like i'm always searching for a reason to angry. Also there are some thing you can never have control and i need to accept that. I know i can't but i really need to not fall in desire and aversion. Thinngs need to change and only i can change. It's frustrating i always find some reason or n general word, excuse. Procrastination is killing me . Leaving everything for tommorow.

* 2022

** 2022-03 March

*** 2022-03-04 Friday
